# Generated by Django 4.2.6 on 2023-10-08 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenValue', models.CharField(max_length=512)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('delete_date', models.DateField(null=True)),
            ],
        ),
    ]
