# Generated by Django 4.2.6 on 2023-10-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='tokenValue',
            new_name='token_value',
        ),
    ]
