# Generated by Django 4.2.6 on 2023-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_token_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='delete_date',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
