# Generated by Django 4.2.6 on 2023-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
